import { CommonModule } from '@angular/common';
import { Component, OnInit, OnDestroy, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { Router, ActivatedRoute, RouterModule } from '@angular/router';

import { HeaderService } from '../../core/services/header.service';
import { NotificationService } from '../../core/services/notification.service';
import { FitService } from './fit.service';
import { FitSessionDetail } from './fit.model';

type FitThreadItemVm = {
  id: string;
  sessionDate: string;
  title: string;
  text: string;
  status: number;
};

@Component({
  selector: 'app-fit-thread',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
  ],
  templateUrl: './fit-thread.html',
  styleUrl: './fit-thread.scss',
})
export class FitThread implements OnInit, OnDestroy {
  public fitService = inject(FitService);
  private headerService = inject(HeaderService);
  private notificationService = inject(NotificationService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  loading = signal(false);
  threadItems = signal<FitThreadItemVm[]>([]);

  ngOnInit() {
    this.headerService.setConfig({
      actions: [
        {
          label: 'Refresh',
          icon: 'refresh',
          type: 'secondary',
          onClick: () => this.loadThread(),
        },
        {
          label: 'New Session',
          icon: 'add',
          type: 'primary',
          onClick: () =>
            this.router.navigate(['../new'], { relativeTo: this.route }),
        },
      ],
    });

    this.loadThread();
  }

  ngOnDestroy() {
    this.headerService.clear();
  }

  async loadThread() {
    this.loading.set(true);
    try {
      const details = await this.fitService.fetchRecentThreadDetails(15);

      const items = details.map((detail) => ({
        id: detail.session.tb_tyapp_fit_ssn_id,
        sessionDate: detail.session.session_date,
        title: detail.session.session_title?.trim() || 'Untitled Session',
        status: detail.session.status,
        text: this.buildThreadText(detail),
      }));

      this.threadItems.set(items);
    } finally {
      this.loading.set(false);
    }
  }

  onEdit(id: string) {
    this.router.navigate(['../edit', id], {
      relativeTo: this.route,
      queryParams: { returnUrl: '/fit/thread' },
    });
  }

  async copyText(text: string) {
    try {
      await navigator.clipboard.writeText("[This content is generated by TY Web App]\n" + text);
      this.notificationService.showSuccess('已複製到剪貼簿');
    } catch (err) {
      this.notificationService.handleError('複製失敗，請手動選取', err);
    }
  }

  private buildThreadText(detail: FitSessionDetail): string {
    const lines: string[] = [];
    const session = detail.session;

    let header = `${session.session_date}：`;
    if (session.session_title?.trim()) {
      header += `\n${session.session_title.trim()}`;
    }
    lines.push(header);

    if (session.remarks?.trim()) {
      lines.push(session.remarks.trim());
    }
    lines.push('');

    detail.entries.forEach((entry) => {
      lines.push(entry.exercise_name || '未命名動作');

      if (
        entry.entry_type === 'strength' ||
        entry.entry_type === 'bodyweight'
      ) {
        const groupedSets: { str: string; count: number }[] = [];
        let currentGroup: { str: string; count: number } | null = null;

        entry.sets.forEach((set) => {
          let setStr = '';
          if (set.weight_value)
            setStr += `${set.weight_value}${set.weight_unit || ''}`;
          if (set.reps_value)
            setStr += setStr ? `×${set.reps_value}` : `${set.reps_value}下`;
          if (!setStr) setStr = '完成';

          if (currentGroup && currentGroup.str === setStr) {
            currentGroup.count++;
          } else {
            if (currentGroup) groupedSets.push(currentGroup);
            currentGroup = { str: setStr, count: 1 };
          }
        });
        if (currentGroup) groupedSets.push(currentGroup);

        groupedSets.forEach((g) => {
          lines.push(g.count > 1 ? `${g.str}×${g.count}` : `${g.str}×1`);
        });
      } else {
        entry.sets.forEach((set) => {
          const parts = [];
          if (set.level_text) parts.push("Level " + set.level_text);
          if (set.duration_sec) {
            const mins = Math.floor(set.duration_sec / 60);
            const secs = set.duration_sec % 60;
            parts.push(
              `時間${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`,
            );
          }
          if (set.calories_value) parts.push(`Calories ${set.calories_value}`);
          if (set.reps_value) parts.push(`${set.reps_value}下`);

          if (parts.length > 0) lines.push(parts.join('\n'));
        });
      }

      if (entry.remarks?.trim()) {
        lines.push(`（${entry.remarks.trim()}）`);
      }
      lines.push('');
    });

    return lines.join('\n').trim();
  }
}
